# Generated by Django 5.0.7 on 2024-09-22 17:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Picture'),
        ),
    ]
