# Generated by Django 5.0.7 on 2024-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contributor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
